# Generated by Django 4.1.3 on 2022-11-14 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filme', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filme',
            name='categoria',
            field=models.CharField(choices=[('Acao', 'Ação'), ('Anime', 'Anime'), ('Aventura', 'Aventura'), ('Comedia', 'Comédia'), ('Documentario', 'Documentário'), ('Infantil', 'Infantil'), ('Romance', 'Romance'), ('Terror', 'Terror'), ('Drama', 'Drama')], max_length=16),
        ),
    ]
